# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-07 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentevent',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentevent',
            name='modified',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
