defaults: &defaults
  working_directory: ~/hausmate

version: 2
jobs:
  build:
    <<: *defaults
    docker:
      - image: circleci/python:3.6.2
        environment:
          DJANGO_DEBUG: 'True'
          DJANGO_SETTINGS_MODULE: 'settings.base'
    steps:
      - checkout
      - restore_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install --upgrade pip setuptools
            pip install -r requirements.txt
      - save_cache:
          key: deps1-{{ .Branch }}-{{ checksum "requirements.txt" }}
          paths:
            - "venv"
      - run:
          command: |
            . venv/bin/activate
            python manage.py test
      - store_artifacts:
          path: test_reports/
          destination: tr1

  deploy:
    <<: *defaults
    docker:
      - image: google/cloud-sdk
    steps:
      - checkout

      - run:
          command: |
            pip install jinja2-cli
      - run:
          name: Authenticate with GCP
          command: |
            echo $GCLOUD_SERVICE_KEY | base64 --decode --ignore-garbage > ${HOME}/gcloud-service-key.json
            export GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcloud-service-key.json
            gcloud auth activate-service-account --key-file $GOOGLE_APPLICATION_CREDENTIALS --project=$GOOGLE_PROJECT_ID

      - run:
          name: Deploy to Google App Engine
          command: |
            jinja2 -D "DB_CONNECTION_NAME=$DB_CONNECTION_NAME" \
              -D "DB_NAME=$DB_NAME" -D "DB_PASSWORD=$DB_PASSWORD" \
              -D "DB_USER=$DB_USER" -D "GOOGLE_PROJECT_ID=$GOOGLE_PROJECT_ID" \
              app.template.yaml > app.yaml
            gcloud app deploy -q


workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
