# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 02:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_house_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='house',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='houses.House'),
        ),
    ]
