# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 03:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_bill_house'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Bill')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Roommate')),
            ],
        ),
    ]
