# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 04:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0005_auto_20171106_0306'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='houses.Payment')),
            ],
        ),
    ]
