# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-06 05:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_paymentevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='due_date',
            field=models.DateTimeField(null=True),
        ),
    ]
